credentials:
  usernames:
      admin:
        password: $2b$12$KiPu50dxWHCrMpoUy4ztC.18vdb/kaEQr71hIz8v.GYhha2qunQ7e
        # رمز عبور: elnagh
      
      fin.analyst:
        password: $2b$12$ejRAnTtsyZrjpo7jrnNNo.2PDVzZ.cGxIhJRlDrpJKn4w2/bDvPyW
        # رمز عبور: abc_fin_cba
      
      h.khandani:
        password: $2b$12$61q/gw2lT5o0Ft0iY7fb6ewGpob3NiVQzbIJH/wsLUL1AL0wAthja
        # رمز عبور: 123

cookie:
  name: financial_analyzer_cookie
  key: random_signature_key_financial_2024_secure_xyz123
  expiry_days: 30

preauthorized:
  emails:
    - admin@example.com
